astra_db:
  collection_name: "role-based-rag-application"

embedding_model:
  provider: "gemini"
  model_name: models/embedding-001

retriever:
  top_k: 10

llm:
  provider: "gemini"
  model_name: gemini-pro
