astra_db:
  collection_name:"role-based-rag-application"

embedding_model:
  provider: "gemini"
  model_name: models/embedding-001 # Or another suitable Gemini embedding model # or use OpenAI embedding if needed

retriever:
  top_k: 10

llm:
  provider: "gemini"
  model_name: gemini-pro # Or gemini-1.5-pro, gemini-2.0-flash, etc    # or "gpt-4-1106-preview" or "gpt-3.5-turbo"
  

